//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Essay_Analysis_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Essay_Analysis_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*).
        /// </summary>
        internal static string AllFileTypes {
            get {
                return ResourceManager.GetString("AllFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v2.0.0.SNAPSHOT.
        /// </summary>
        internal static string ApplicationVersion {
            get {
                return ResourceManager.GetString("ApplicationVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Batch file (*.bat).
        /// </summary>
        internal static string BatchFileType {
            get {
                return ResourceManager.GetString("BatchFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# source file (*.cs).
        /// </summary>
        internal static string CSharpFileType {
            get {
                return ResourceManager.GetString("CSharpFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyper Text Markup Language File (*.html).
        /// </summary>
        internal static string HTMLFileType {
            get {
                return ResourceManager.GetString("HTMLFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid argument has been passed into the function!.
        /// </summary>
        internal static string InvalidArgument {
            get {
                return ResourceManager.GetString("InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename is null, empty, or whitespace!.
        /// </summary>
        internal static string InvalidFilename {
            get {
                return ResourceManager.GetString("InvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Java source file (*.java).
        /// </summary>
        internal static string JavaFileType {
            get {
                return ResourceManager.GetString("JavaFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javascript source file (*.js).
        /// </summary>
        internal static string JSFileType {
            get {
                return ResourceManager.GetString("JSFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file (*.json).
        /// </summary>
        internal static string JSONFileType {
            get {
                return ResourceManager.GetString("JSONFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua source file (*.lua).
        /// </summary>
        internal static string LuaFileType {
            get {
                return ResourceManager.GetString("LuaFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal text file (*.txt).
        /// </summary>
        internal static string NormalTextFileType {
            get {
                return ResourceManager.GetString("NormalTextFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastColoredTextBox is null!.
        /// </summary>
        internal static string NullFastColoredTextBox {
            get {
                return ResourceManager.GetString("NullFastColoredTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATabStrip is null!.
        /// </summary>
        internal static string NullTabStrip {
            get {
                return ResourceManager.GetString("NullTabStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FATabStripItem is null!.
        /// </summary>
        internal static string NullTabStripItem {
            get {
                return ResourceManager.GetString("NullTabStripItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHP file (*.php).
        /// </summary>
        internal static string PHPFileType {
            get {
                return ResourceManager.GetString("PHPFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Query Language file (*.sql).
        /// </summary>
        internal static string SQLFileType {
            get {
                return ResourceManager.GetString("SQLFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Basic file (*.vb).
        /// </summary>
        internal static string VBFileType {
            get {
                return ResourceManager.GetString("VBFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VBScript file (*.vbs).
        /// </summary>
        internal static string VBSFileType {
            get {
                return ResourceManager.GetString("VBSFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensible Markup Language file (.xml).
        /// </summary>
        internal static string XMLFileType {
            get {
                return ResourceManager.GetString("XMLFileType", resourceCulture);
            }
        }
    }
}
